# Generated by Django 4.2.6 on 2023-11-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role_alter_customuser_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_product_owner',
            field=models.BooleanField(default=False),
        ),
    ]
