# Generated by Django 4.2.6 on 2023-11-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_is_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_scrum_master',
            field=models.BooleanField(default=False),
        ),
    ]
